Fixes:
ERROR:  function create_point(integer, bigint) does not exist at character 13
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2020-07-25 00:36:31.707 UTC [86] QUERY:  SELECT box (create_point(0, $1), create_point($2,500000000))
CONTEXT:  SQL function "boxrange" during inlining
automatic analyze of table "machadosample.public.featureloc"